# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0014_film_is_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file_name', models.CharField(max_length=250, unique=True)),
                ('file_extension', models.CharField(max_length=10)),
                ('file_size', models.CharField(max_length=10, null=True)),
                ('poster', models.CharField(max_length=250, null=True)),
                ('background', models.CharField(max_length=250, null=True)),
                ('first_air_date', models.DateField(null=True)),
                ('movie_db_id', models.IntegerField(default=0, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('overview', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='films.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshows.Show'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshows.Season'),
        ),
    ]
