# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='resolution',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
