# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0002_episode_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='resolution',
        ),
    ]
