# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20170904_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='is_vieved',
            new_name='is_viewed',
        ),
    ]
