# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20170904_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='background',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='file_size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='first_air_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
