# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20170906_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='movie_db_id',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
