# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_film_movie_db_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='movie_db_id',
            field=models.IntegerField(null=True),
        ),
    ]
