# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20170906_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
