# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_auto_20170906_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='file_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
