# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_auto_20170907_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
